window.loading_lines = [
  "Finally loading",
  "Searching Memes",
  "Giving up \u0028\u256f\u00b0\u25a1\u00b0\uff09\u256f\ufe35\u0020\u253b\u2501\u253b",
  "Not Giving Up \u252c\u2500\u252c\u0020\u30ce\u0028\u0020\u309c\u002d\u309c\u30ce\u0029",
  "I don't even know what to put here \u00af\u005f\u0028\u30c4\u0029\u005f\u002f\u00af",
  "One Time, I saw a bird...",
  "How To Find Your Dog [Not ClickBait] [Gone WRONG]",
  "How To Double Your Wifi Speed (REALY WORKS)",
  "Calculating \"the meme\" Variable",
  "Divising the color red",
  "Removing the speed limiter",
  "Coming Up With New Fluff Text",
  "Mentioning B1nzy",
  "Building a machine to kill God",
  "Filling with juicy berries",
  "Large Holly 1x1 $15",
  "Inserting Tic Tacs",
  "Translating From Portuguese",
  "Calibrating Cafuné Machine",
  "Opening At least 3 ports",
  "Hi User, I'm Loading",
  "Opening a trading card pack",
  "Generating usb fans",
  "Locating someone named \"Bill\"",
  "ur mom loads slow",
  "Making Free Energy",
  "Several people loading",
  "Stretching The \"Rules\"",
  "Banning Fidget Spinners",
  "The Word \"Meme\"",
  "Harvesting surplus rapeseed",
  "Nothing: what did you expect?",
  "Please insert quarter",
  "Giving cats and dogs hammers",
  "Dialing AOL",
  "Here hold this",
  "Ending it all",
  "Feeding dinosaurs",
  "Acting straight",
  "It's already loaded",
  "covfefe",
  "Look behind you",
  "If it is, where is?",
  "Do you handle this",
  "Why is it so small?",
  "Going incognito",
  "Did you remember to clear your history?",
  "Turning off Safe Search",
  "Are you an Edge user?",
  "When nothing is going right, go left",
  "Awoooooooooooo",
  "Loading 99%",
  "You have the right to remain stupid",
  "Is the answer 42?",
  "Watching a Music Bot Tutorial",
  "Documenting Discord's API",
  "Banning blobs",
  "IP banning...",
  "Generic sucks",
  "Ratelimit me, daddy",
  "Litecord machine broke",
  "Pinging @everyone for nothing...",
  "Ever heard of a man called José?",
  "Making it harder, better, faster and stronger...",
  "Read the FAQ's",
  "Remember, it's only a theory...",
  "Making it awkward...",
  "Don't forget to hydrate",
  "Recounting phrases...",
  "Listening for new posts on /r/dankmemes",
  "*Whirring sounds*",
  "Decompiling Discord",
  "Copy-pasting source",
  "Recompiling cake",
  "D o w n l o a d   m e m e s ?",
  "Leaking memory",
  "Getting caffeine fix",
  "🅱enis?️ 🅱enis. 🅱🅱🅱🅱🅱🅱🅱🅱ENISSSSSSSSS!",
  "Hacking into CCTV cameras...",
  "Hijacking insecured printers to print \"MEMEWORK MAKES THE DREAM WORK\"",
  "<Thonk emoji>",
  "Tiem fer Slep",
  "H E N L O ?",
  "NYEHEHEHEHE",
  "Adding language packs...",
  "You loaded how many plugins?!?!?!?",
  "A A A A A PLS SEND THE READY EVENT U 🅱ENIS",
  "Ingesting 🅱enis",
  "🅱enis 🅱achine 🅱roke",
  "🅱e the 🅱oading 🅱achine 🅱ou",
  "oof",
  "Playing ROBLOX",
  "Thonking about itself",
  "I'm conscious but you guys don't believe",
  "Opening WhatsApp...",
  "Opening Telegram...",
  "Opening Discord...",
  "Opening Teamspeak",
  "Destroying your backups",
  "sanic: gotta go fast.",
  "Creating tons of bots",
  "Charging your battery in the speed of light",
  "You should get water, its important.",
  "Zzz... oh shit its time to load",
  "Playing podcasts",
  "You don't really like me, do you?"
]
