window.loading_lines = [
  "Finally loading",
  "Searching Memes",
  "Giving up (╯°□°）╯︵ ┻━┻",
  "Not Giving Up ┬─┬﻿ ノ( ゜-゜ノ)",
  "I don't even know what to put here ¯\_(ツ)_/¯",
  "One Time, I saw a bird...",
  "How To Find Your Dog [Not ClickBait] [Gone WRONG]",
  "How To Double Your Wifi Speed (REALY WORKS)",
  "Calculating \"the meme\" Variable",
  "Divising the color red",
  "Removing the speed limiter",
  "Coming Up With New Fluff Text",
  "Mentioning B1nzy",
  "Building a machine to kill God",
  "Filling with juicy berries",
  "Large Holly 1x1 $15",
  "Inserting Tic Tacs",
  "Translating From Portuguese",
  "Calibrating Cafuné Machine",
  "Opening At least 3 ports",
  "Hi User, I'm Loading",
  "Opening a trading card pack",
  "Generating usb fans",
  "Locating someone named \"Bill\"",
  "ur mom loads slow",
  "Making Free Energy",
  "Several people loading",
  "Stretching The \"Rules\"",
  "Banning Fidget Spinners",
  "The Word \"Meme\"",
  "Harvesting surplus rapeseed",
  "Nothing: what did you expect?",
]